AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'bin/*'
    - 'vendor/**/*'
    - 'config/environments/*'
    - 'client/**/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'


