jobs:
  include:
    - language: ruby
      install:
        - gem update --system
        - bundle install --jobs=3 --retry=3 --deployment
      stage: lint
      rvm: 2.5.3
      script: bundle exec rubocop

    - language: node_js
      node_js: 10.16.0
      install: cd client && npm install
      script: npm run eslint

    - language: node_js
      node_js: 10.16.0
      install: cd client && npm install
      script: npm run stylelint

    - language: ruby
      install:
        - gem update --system
        - bundle install --jobs=3 --retry=3 --deployment
      stage: test
      rvm: 2.5.3
      env:
        - RAILS_ENV=test
      script: bundle exec rake

    - language: node_js
      node_js: 10.16.0
      install: cd client && npm install
      script: npm run test
