jobs:
  include:
    - stage: lint
      language: ruby
      rvm: 2.5.3
      script: bundle exec rubocop

    - language: node_js
      node_js: 10.16.0
      install: cd client && npm install
      script: npm run eslint

    - language: node_js
      node_js: 10.16.0
      install: cd client && npm install
      script: npm run stylelint

    - stage: test
      language: ruby
      rvm: 2.5.3
      env:
        - RAILS_ENV=test
      script: bundle exec rake
